begin;

create table public.preventa_default_acl_probe (
  id bigint generated by default as identity primary key
);

do $$
begin
  if has_table_privilege('anon','public.preventa_default_acl_probe','SELECT')
     or has_table_privilege('anon','public.preventa_default_acl_probe','INSERT')
     or has_table_privilege('authenticated','public.preventa_default_acl_probe','SELECT')
     or has_table_privilege('authenticated','public.preventa_default_acl_probe','INSERT') then
    raise exception 'DEFAULT ACL TEST FAILED: client roles inherited privileges on future public table';
  end if;

  if has_sequence_privilege(
       'anon',
       pg_get_serial_sequence('public.preventa_default_acl_probe','id'),
       'USAGE'
     )
     or has_sequence_privilege(
       'authenticated',
       pg_get_serial_sequence('public.preventa_default_acl_probe','id'),
       'USAGE'
     ) then
    raise exception 'DEFAULT ACL TEST FAILED: client roles inherited privileges on future public sequence';
  end if;

  if not has_table_privilege('service_role','public.preventa_default_acl_probe','SELECT') then
    raise exception 'DEFAULT ACL TEST FAILED: service_role lost expected server-side table access';
  end if;
end
$$;

rollback;

select 'PREVENTA_DEFAULT_PRIVILEGES_FAIL_CLOSED_OK' as result;